In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({'text':['people watch Netflix','Netflix watch Netflix','people write reviews','Netflix write reviews'],'output':[1,1,0,0]})
data

text  output
0   people watch Netflix       1
1  Netflix watch Netflix       1
2   people write reviews       0
3  Netflix write reviews       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(data['text'])
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [6]:
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'netflix': 0, 'write': 4, 'reviews': 2}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 1 0 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 0 1 0 1]]


In [8]:
cv.transform(["Netflix watch and write reviews of Netflix"]).toarray()

array([[2, 0, 1, 1, 1]], dtype=int64)